### PR TITLE
[WIP] Combine objects and resources and added relations fixes #42

### LINKED ISSUE #42: Add getters to fetch related resources
Create a nice way to fetch related resources for an object, e.g. all refunds for a payment or all mandates for a customer.

For some relations an entry is added to the `links` property. See the [GET Payments documentation](https://www.mollie.com/en/docs/reference/payments/get) for an example.

For others we should determine the URL ourself, for example by using the customer's ID to fetch the mandates ([documentation](https://www.mollie.com/en/docs/reference/mandates/list)).

### PR DESCRIPTION
**Pull request by benoist**
I've simplified the library by removing the API module. I also combined the objects and the resources to make them act more like data models as seen in ActiveRecord and DataMapper.
The new relation model allows for easy access to related resources #42 

With this version the api changes like show here:

```ruby
# Old style
client  = Mollie::API::Client.new("test_dHar4XY7LxsDOtmnkVtjNVWXLSlXsM")
payment = client.payments.create(amount: 1.95)
payment = client.payments.get("tr_7UhSN1zuXS")
refund  = client.payment_refunds.with("tr_7UhSN1zuXS").create(amount: 1.10)
refunds = client.payment_refunds.with("tr_7UhSN1zuXS").all

# New style
payment = Mollie::Payment.create(amount: 1.95)
payment = Mollie::Payment.get("tr_7UhSN1zuXS")
refund  = payment.refunds.create(amount: 1.10)
refunds = payment.refunds.all
```

Configuration of the client will require the following code when the application is initialized
For example
```ruby
# Rails config/initializers/mollie.rb
Mollie::Client.configure do |client|
  client.api_key = "test_dHar4XY7LxsDOtmnkVtjNVWXLSlXsM"
end

# Sinatra
configure :production, :development do
  Mollie::Client.configure do |client|
    client.api_key = "test_dHar4XY7LxsDOtmnkVtjNVWXLSlXsM"
  end
end
```

/cc @Daanvm @justincase @mvz any comments?

Remaining tasks are
- [x] Add client configuration and allow per request api key changes
- [x] use the new style in the examples 
- [ ] remove the old style API

### CODE REVIEW

**Comment by mvz** [comment]
I like the dropping of the API namespace, but for the purpose of testing and possibly for the ability to connect to more than one Mollie account at the same time, I prefer having the client object with the contained key. Plain `Mollie::Client.new()` could create one with the default configured key, though.

**Comment by mvz** [comment]
`payment.refunds.create(amount: 1.10)` is definitely an improvement over `client.payment_refunds.with("tr_7UhSN1zuXS").create(amount: 1.10)` 👍

**Comment by benoist** [comment]
> I prefer having the client object with the contained key. Plain Mollie::Client.new()

Hmmm thats not really going to work as you would directly initialize the client when creating a new payment.
In a controller action or background job you would just use

```ruby
def new
  Mollie::Payment.create(amount: 1.0)
end
```

What I was thinking to create is a utility function to change the API key in the block

```ruby
def new
  Mollie::Util.with_api_key("other_key") do
    payment = Mollie::Payment.create(amount: 1.0)
    redirect_to payment.redirect_url
  end
end
```

Other option is

```ruby
def new
  payment = Mollie::Payment.create(amount: 1.0, api_key: "other_key")
  redirect_to payment.redirect_url
end
```

Using a block may be preferred if you have multiple api calls to make with the same key.
Using the param api_key override can be handy if you only have 1 api call to make.

I can also make it so you can override the current client

```ruby
def new
  Mollie::Client.instance = Mollie::Client.new("api_key")
  payment = Mollie::Payment.create(amount: 1.0, api_key: "other_key")
end
```
So you can initialize it in a before filter or when you run tests.
Any thoughts?

**Comment by Thijs-Riezebeek** [comment]
I am not too familiar with Ruby, so I don't know if Dependency Injection is very common.

That is my main concern with this approach. All of the initial interactions with the Mollie API/Client are static. This makes editing settings like `api_url` and `api_key` static/global, instead of having an instance of a client that can be modified or instantiated differently.

On top of that, testing might be harder, since everything is static (no mock of the API client can be inserted via DI).

**Comment by benoist** [comment]
Yes it's all static, the question is what will change often. I don't think api_url will change.
api_key can change if using the connect api, but it's only the API key. I proposed a few ways to solve that and can probably come up with more if required.

For testing purposes, I wonder what you would mock or stub. With the new style you can easily mock or stub the Payment.create method or expect it to be called. You don't really need to test or assert that the correct endpoint is called, as this functionality is already tested in the library itself.

**Comment by Thijs-Riezebeek** [comment]
How would you prevent the static call to `Payment.create()` from actually executing an API call when running your tests? And how would you assert that it is called? In PHP this is not possible (or hard at the very least).

**Comment by mvz** [comment]
> > I prefer having the client object with the contained key. Plain Mollie::Client.new()
> Hmmm thats not really going to work as you wouldn't directly initialize the client when creating a new payment.

Yes. My point was
1. That I prefer the way this is done in the old design.
2. That you can still have a global default API key

> Using a block may be preferred if you have multiple api calls to make with the same key.
> Using the param api_key override can be handy if you only have 1 api call to make.

Either way is not great if you want to extract methods that don't have to know about the API key but still need to access multiple accounts.

> I can also make it so you can override the current client

That seems dangerous as you're creating even more global state.

> With the new style you can easily mock or stub the Payment.create method or expect it to be called.

I vastly prefer stubbing an object over stubbing a class, but yes, it would be possible to do it this way.

**Comment by mvz** [comment]
Please note that I think you can solve #42 while still starting from the `Mollie(::API)::Client` object:

```ruby
client  = Mollie::API::Client.new("test_dHar4XY7LxsDOtmnkVtjNVWXLSlXsM")
payment = client.payments.create(amount: 1.95)
payment = client.payments.get("tr_7UhSN1zuXS")
refund  = payment.refunds.create(amount: 1.10)
refunds = payment.refunds.all
```

**Comment by benoist** [comment]
```ruby
payment = client.payments.get("tr_7UhSN1zuXS")
refund  = payment.refunds.create(amount: 1.10)
refunds = payment.refunds.all
```
This only works if payment has a reference to the client instance, which means a Payment would have a client instance variable. It's definitely possible to solve the issue that way, but when retrieving a list, you would have to add that reference to each object returned in the list. Not sure if that is such a good idea.

**Comment by benoist** [comment]
Other things that also wouldn't work are:

```ruby
refunds = Mollie::Payment.new(id: "tr_ tr_7UhSN1zuXS").refunds.all
refunds = Mollie::Payment::Refund.all(payment_id: "tr_7UhSN1zuXS")
```

When you start with the client it would be more like the old style
```ruby
refunds = client.payment_refunds.all(payment_id: "tr_7UhSN1zuXS")
```

I can also turn it around and make something like
```ruby
Mollie::Payment.connect(client).get("tr_7UhSN1zuXS")
```

Global state can be contained to a request and response cycle by using a block to wrap your actions. 

```ruby
# Sinatra
get '/payments' do
  Mollie::Client.connect(api_key) do
    payment = Mollie::Payment.create(amount: 1.0)
    redirect payment.redirect_url
  end
end

# Rails
class PaymentsController < ApplicationController
  around_action :set_client

  def new
    payment = Mollie::Payment.create(amount: 1.0)
    redirect_to payment.redirect_url
  end

  private

  def set_client(&block)
    Mollie::Client.connect(api_key, &block)
  end
end

# Sidekiq worker
class PaymentJob < Job
  def perform(payment_id, api_key)
    Mollie::Client.connect(api_key) do
      payment = Mollie::Payment.get(payment_id)

      if payment.paid?
        Order.where(payment_id: payment_id).update_all(paid: true)
      end
    end
  end
end
```

I think that you would only use 1 api key per request response cycle or background job. But please correct me if I'm wrong as I don't use the Mollie oAuth keys.

**Comment by mvz** [comment]
> It's definitely possible to solve the issue that way, but when retrieving a list, you would have to add that reference to each object returned in the list. Not sure if that is such a good idea.

I think it's fine for each object to known its API client. It's hard to say whether there would be any performance issues in practice.

> I think that you would only use 1 api key per request response cycle or background job. But please correct me if I'm wrong as I don't use the Mollie oAuth keys.

Probably. I still think the design that starts from a client instance is cleaner and less limiting.

Supporting the block and around_action options will need to consider thread safety. It's up to you whether you think that's worth it, I guess.

**Comment by benoist** [comment]
> Supporting the block and around_action options will need to consider thread safety

Yes that is definitely a must, but thats easy to deal with.

> It's up to you whether you think that's worth it, I guess.

I think both approaches have pros and cons.

Starting from the client:
- Client objects can be initialized where required
- Adding resources requires code changes in the client class
- Resources need to be initialized with a references to the client

Starting from the resource object:
- Singleton client required per thread/context (request, job, script)
- Adding resources does not require code changes in the client class
- Resources can be initialized without adding an explicit reference to the client.

**Comment by Thijs-Riezebeek** [comment]
Is it still possible to do everything from the client after this change (e.g. Calls such as `payment.refunds.all()` are simply a facade for the actual calls to the `Client`)?

**Comment by benoist** [comment]
> Is it still possible to do everything from the client after this change (e.g. Calls such as payment.refunds.all() are simply a facade for the actual calls to the Client)?

I was thinking to at least support that in the beginning to stay backwards compatible. Internally it would work a bit different, but the library API stays the same.

**Comment by Thijs-Riezebeek** [comment]
If the intention is to remove the old way of doing calls (via the `Client`), then I'd suggest marking those methods as deprecated in the code, so that developers are aware of it and can start to move away from it.

**Comment by benoist** [comment]
I talked to @justincase today and he suggested to have a look at the Stripe API.
They also use a Resource based approach over a Client based approach. https://github.com/stripe/stripe-ruby#usage

```ruby
require "stripe"

# Global API Key
Stripe.api_key = "sk_test_..."

# Per request API key
Stripe::Charge.list(
  {},
  :api_key => "sk_test_...",
  :stripe_account => "acct_..."
)
```

**Comment by Thijs-Riezebeek** [comment]
Since there aren't any real problems with making this static, I'm al for it. Go ahead :)

**Comment by mvz** [comment]
It's nice that Stripe allows passing the api_key per request.

**Comment by benoist** [comment]
Yeah so it's what I proposed earlier as well

```ruby
def new
  payment = Mollie::Payment.create(amount: 1.0, api_key: "other_key")
  redirect_to payment.redirect_url
end
```

**Comment by Thijs-Riezebeek** [comment]
Perhaps that is something to consider for all options that can be set globally. To illustrate what this would look like, Guzzle for PHP allows you to configure a `GuzzleHttp\Client` instance using the `options` parameter. However, each time you call `$client->post()`, you can also pass an `options` parameter. This `options` parameter allows you to set exactly the same options/settings as on the `Client`, but they will only be set for that specific request and they will always override the general settings from the `Client instance`.

**Comment by benoist** [comment]
@Thijs-Riezebeek that would be easy to do. It's only the endpoint and api key parameter that need special handling. All the other options are already added to the request params.

**Pull request merged**
